import { useState } from 'preact/hooks';

function CampoPassword({ etiqueta, valor, onInput, visible, onAlternar, minLength }) {
  return <label class="grid gap-1.5 text-sm font-semibold text-slate-700">{etiqueta}<span class="relative"><input type={visible ? 'text' : 'password'} value={valor} onInput={onInput} minLength={minLength} required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 pr-12 font-normal outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /><button type="button" onClick={onAlternar} aria-label={visible ? `Ocultar ${etiqueta.toLowerCase()}` : `Mostrar ${etiqueta.toLowerCase()}`} aria-pressed={visible} class="absolute inset-y-0 right-0 px-3 text-lg text-slate-400 hover:text-indigo-600">{visible ? '◉' : '◌'}</button></span></label>;
}

function Login({ onLogin, onRegister }) {
  const [registro, setRegistro] = useState(false); const [nombre, setNombre] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmacion, setConfirmacion] = useState(''); const [mostrarPassword, setMostrarPassword] = useState(false); const [mostrarConfirmacion, setMostrarConfirmacion] = useState(false); const [error, setError] = useState(''); const [enviando, setEnviando] = useState(false);
  const coinciden = registro && password.length > 0 && confirmacion.length > 0 && password === confirmacion;
  const noCoinciden = registro && confirmacion.length > 0 && password !== confirmacion;
  const enviar = async (event) => { event.preventDefault(); setError(''); if (registro && password !== confirmacion) { setError('Las contraseñas no coinciden.'); return; } setEnviando(true); try { if (registro) await onRegister({ nombre, email, password }); else await onLogin({ email, password }); } catch (problema) { setError(problema.message); } finally { setEnviando(false); } };
  const volverLogin = () => { setRegistro(false); setError(''); setPassword(''); setConfirmacion(''); };
  return <main class="grid min-h-screen place-items-center bg-gradient-to-br from-indigo-700 via-indigo-600 to-cyan-500 px-4 py-8"><form onSubmit={enviar} class="w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl sm:p-9">{registro && <button type="button" onClick={volverLogin} class="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-indigo-600" aria-label="Volver al inicio de sesión"><span class="text-xl leading-none">←</span> Volver al login</button>}<div class="mb-8"><span class="inline-flex size-11 items-center justify-center rounded-2xl bg-indigo-100 text-xl text-indigo-700">▦</span><p class="mt-5 text-sm font-semibold tracking-widest text-indigo-600 uppercase">Inventario simple</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900">{registro ? 'Crear cuenta' : 'Bienvenido de nuevo'}</h1><p class="mt-2 text-slate-500">{registro ? 'Regístrate para administrar tus productos.' : 'Ingresa para continuar.'}</p></div><div class="grid gap-4">{registro && <label class="grid gap-1.5 text-sm font-semibold text-slate-700">Nombre<input type="text" value={nombre} onInput={(event) => setNombre(event.currentTarget.value)} required class="rounded-xl border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label>}<label class="grid gap-1.5 text-sm font-semibold text-slate-700">Email<input type="email" value={email} onInput={(event) => setEmail(event.currentTarget.value)} required class="rounded-xl border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label><CampoPassword etiqueta="Contraseña" valor={password} onInput={(event) => setPassword(event.currentTarget.value)} visible={mostrarPassword} onAlternar={() => setMostrarPassword(!mostrarPassword)} minLength="8" />{registro && <><CampoPassword etiqueta="Confirmar contraseña" valor={confirmacion} onInput={(event) => setConfirmacion(event.currentTarget.value)} visible={mostrarConfirmacion} onAlternar={() => setMostrarConfirmacion(!mostrarConfirmacion)} minLength="8" />{noCoinciden && <p class="-mt-2 text-xs font-medium text-rose-600">Las contraseñas no coinciden.</p>}{coinciden && <p class="-mt-2 text-xs font-medium text-emerald-600">Las contraseñas coinciden.</p>}</>}{error && <p role="alert" class="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<button type="submit" disabled={enviando || noCoinciden} class="rounded-xl bg-indigo-600 px-4 py-3 font-semibold text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:bg-indigo-300">{enviando ? 'Procesando...' : registro ? 'Crear cuenta' : 'Ingresar'}</button>{!registro && <button type="button" onClick={() => { setRegistro(true); setError(''); }} class="pt-1 text-sm font-semibold text-indigo-600 hover:text-indigo-800">Crear una cuenta nueva</button>}</div></form></main>;
}
export default Login;
